common:
  max_ts: 100000
  gamma: 0.99
  batch_size: 200
env:
  # name: CartPole-v0
  name: PongNoFrameskip-v4
  # name: Pendulum-v0
  # name: QbertNoFrameskip-v4
solver:
  name: 'ppo'
  # sgd_minibatch_size: 100
  # train_batch_size: 500
  k_epochs: 10
  eps_clip: 0.2
  vf_loss_coeff: 1.0
  entropy_coeff: 0.01
  learning_rate: 0.0001
trainer:
  print_interval: 100
worker:
  print_interval: 5000
  exploration: 1,0.01,30000
